import { verificarFechaNavidad } from "./Estructuras_anidadas/navidad.js";
import { condicionales_compuestas_actividad1, condicionales_compuestas_actividad2 } from "./Estructuras_condicionales/condicionales_compuestas.js";
import { condicionales_simples_actividad1, condicionales_simples_actividad2 } from "./Estructuras_condicionales/condicionales_simples.js";
import { entrada_datos } from "./Introduccion/entrada_datos.js";
import { variables } from "./Introduccion/variables.js";
import { operadores_logicos_actividad1 } from "./Operadores_logicos/logicos.js";
import { estructura_switch } from "./switch/estructuras_switch.js";
import { estructura_while_actividad1, estructura_while_actividad2 } from "./estructuras_repetitivas/estructuras_while.js";
import { repetivas_acumulador_actividad1, repetivas_acumulador_actividad2 } from "./estructuras_repetitivas/acumulador.js";
import { repetivas_do_while_actividad1 } from "./estructuras_repetitivas/do_while.js";
import { repetivas_for_actividad1 } from "./estructuras_repetitivas/for.js";
import { funciones_actividad1 } from "./funciones/funciones.js";
import { funciones_parametros_actividad1, funciones_parametros_actividad2 } from "./funciones/funciones_parametros.js";
import { funciones_retornan_actividad1, funciones_retornan_actividad2 } from "./funciones/funciones_retornan.js";
import { poo_date_actividad1, poo_date_actividad2 } from "./poo/date.js";
import { poo_array_actividad1, poo_array_actividad2 } from "./poo/array.js";

//entrada_datos();
//variables();
//condicionales_simples_actividad1();
//condicionales_simples_actividad2();
//condicionales_compuestas_actividad1();
//condicionales_compuestas_actividad2();
//condicionales_compuestas_actividad3();
//verificarFechaNavidad();
//operadores_logicos_actividad1();
//estructura_switch();
//estructura_while_actividad1();
//estructura_while_actividad2();
//repetivas_acumulador_actividad1();
//repetivas_acumulador_actividad2();
//repetivas_do_while_actividad1();
//repetivas_for_actividad1();
//funciones_actividad1();
//funciones_parametros_actividad1();
//funciones_parametros_actividad2();
//funciones_retornan_actividad1();
//funciones_retornan_actividad2();
//poo_date_actividad1();
//poo_date_actividad2();
//poo_array_actividad1();
//poo_array_actividad2();